//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonkursyMuzyczne
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdycjeKonkursu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EdycjeKonkursu()
        {
            this.UczestnicyEdycji = new HashSet<UczestnicyEdycji>();
        }
    
        public int IDEdycjiKonkursu { get; set; }
        public int IDKonkursu { get; set; }
        public string NumerEdycji { get; set; }
        public string MiejsceEdycji { get; set; }
        public int LiczbaEtapow { get; set; }
        public Nullable<int> LiczbaUczestnikow { get; set; }
    
        public virtual Konkurs Konkurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UczestnicyEdycji> UczestnicyEdycji { get; set; }
    }
}
