//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonkursyMuzyczne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konkurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Konkurs()
        {
            this.EdycjeKonkursu = new HashSet<EdycjeKonkursu>();
        }
    
        public int IDKonkursu { get; set; }
        public string NazwaKonkursu { get; set; }
        public string RodzajKonkursu { get; set; }
        public Nullable<int> CyklicznoscKonkursu { get; set; }
        public string LokalizacjaKonkursu { get; set; }
        public string ZasiegKonkursu { get; set; }
        public string OrganizatorKonkursu { get; set; }
        public string ZalozycielKonkursu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EdycjeKonkursu> EdycjeKonkursu { get; set; }
    }
}
