//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonkursyMuzyczne
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KonkursyMuzyczne : DbContext
    {
        public KonkursyMuzyczne()
            : base("name=KonkursyMuzyczne")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EdycjeKonkursu> EdycjeKonkursu { get; set; }
        public virtual DbSet<Konkurs> Konkurs { get; set; }
        public virtual DbSet<Uczestnicy> Uczestnicy { get; set; }
        public virtual DbSet<UczestnicyEdycji> UczestnicyEdycji { get; set; }
    }
}
